markdown: kramdown
sass:
  style: :compressed
exclude:
- README.md
- wp-content/README.md
- vendor
permalink: /:categories/:year/:month/:day/

title: Austin JavaScript

description: >
  Austin JavaScript is a meetup group focused on JavaScript and the open web.

twitter:
  user: AustinJS
  url: https://twitter.com/AustinJS

people:
  organizers:
    lawnsea:
      twitter: lawnsea
      full: Lon Ingram
      short: Lon
      avi: /img/people/lawnsea.jpg
      phone: 512-484-0797
    aaron:
      twitter: aaronj1335
      full: Aaron Stacy
      short: Aaron
      avi: /img/people/aaronj1335.jpg
      phone: 812-764-8208
  emeriti:
    joemccann:
      twitter: joemccann
      full: Joe McCann
      short: Joe
      avi: /img/people/joemccann.jpg
    slexaxton:
      twitter: SlexAxton
      full: Alex Sexton
      short: Alex
      avi: /img/people/slex.jpg
